### ISSUE TITLE
Nav

### ISSUE THREAD

**Issue by TheWuilladors** [TheWuilladors/gestion#3]

**Comment by Test-mk1** [comment]
Issue cerrado. A continuacion se enlistan los cambios realizados en el NAV junto a su commit. 

[Commit ID bf0bdc53ea639d0bff6004f1b5d302ec6cdc3dcd](https://github.com/TheWuilladors/gestion/commit/bf0bdc53ea639d0bff6004f1b5d302ec6cdc3dcd)
-Nuevos Estios
-Nuevo Arte

[Commit ID 087030d3c6899b79319ebffad6f74447a2390438](https://github.com/TheWuilladors/gestion/commit/087030d3c6899b79319ebffad6f74447a2390438)
-Nuevos Copys

**Comment by TheWuilladors** [comment]
*NEW*

Generado los siguientes cambios en el nav: Se creo una barra con las categorias de los post asi como tambien se incluyo una barra de busqueda. 

[Commit ID ddd03208a58eb5a9c28b823b503ace6389203eb8](https://github.com/TheWuilladors/gestion/commit/ddd03208a58eb5a9c28b823b503ace6389203eb8)
-Nuevos Estilos visuales de categorias

[Commit ID: a8233cb140446a6ef5e6227b2968849fc632d7c5](https://github.com/TheWuilladors/gestion/commit/a8233cb140446a6ef5e6227b2968849fc632d7c5)
-Nuevos copys en los botones de las categorias
